
const state={games:[],config:{siteName:'كتالوج الألعاب',whatsappNumber:''},platform:null,catalogFilter:'all',page:1,perPage:15,search:'',sort:'releaseYearDesc',cart:[]};
const $=s=>document.querySelector(s);
const byId=id=>document.getElementById(id);
const norm=v=>String(v??'').trim().toLocaleLowerCase('ar');
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function showToast(msg){const t=byId('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function saveCart(){localStorage.setItem('gameInstallCart',JSON.stringify(state.cart));}
function loadCart(){try{const x=JSON.parse(localStorage.getItem('gameInstallCart')||'[]');state.cart=Array.isArray(x)?x:[];}catch{state.cart=[]}}
function allowedGame(g){
  if(state.platform==='PS3') return g.platform==='PS3';
  if(state.platform==='PS4') return g.platform==='PS4';
  if(state.platform==='PS5'){
    if(state.catalogFilter==='PS4') return g.platform==='PS4';
    if(state.catalogFilter==='PS5') return g.platform==='PS5';
    return g.platform==='PS5'||g.platform==='PS4';
  }
  return false;
}
function sortGames(arr){return [...arr].sort((a,b)=>{if(state.sort==='id')return Number(a.id)-Number(b.id);if(state.sort==='releaseYearDesc')return Number(b.releaseYear)-Number(a.releaseYear)||Number(b.id)-Number(a.id);if(state.sort==='releaseYearAsc')return Number(a.releaseYear)-Number(b.releaseYear)||norm(a.name).localeCompare(norm(b.name));return norm(a.name).localeCompare(norm(b.name),'ar');})}
function filteredGames(){const q=norm(state.search);return sortGames(state.games.filter(g=>allowedGame(g)&&(!q||norm(g.name).includes(q)||String(g.id).includes(q)||norm(g.genre).includes(q))));}
function renderGames(){const arr=filteredGames();const totalPages=Math.max(1,Math.ceil(arr.length/state.perPage));if(state.page>totalPages)state.page=totalPages;const start=(state.page-1)*state.perPage;const shown=arr.slice(start,start+state.perPage);const grid=byId('gamesGrid');grid.innerHTML='';byId('emptyState').classList.toggle('hidden',arr.length!==0);for(const g of shown){const added=state.cart.some(x=>String(x.id)===String(g.id));const card=document.createElement('article');card.className='game-card';card.setAttribute('tabindex','0');card.setAttribute('aria-label',`عرض تفاصيل ${g.name}`);card.innerHTML=`<div class="game-image-wrap"><img class="game-image" src="${escapeHtml(g.image)}" alt="${escapeHtml(g.name)}" loading="lazy"></div><div class="game-body"><h3 class="game-title">${escapeHtml(g.name)}</h3><div class="meta"><span>${escapeHtml(g.platform)}</span><span>${escapeHtml(g.size)} GB</span><span>${escapeHtml(g.releaseYear)}</span><span>${escapeHtml(g.genre)}</span></div><button class="add-btn ${added?'added':''}" data-add-id="${escapeHtml(g.id)}" type="button">${added?'✓ تمت الإضافة':'＋ إضافة للطلب'}</button></div>`;grid.appendChild(card);const add=card.querySelector('[data-add-id]');card.addEventListener('click',e=>{if(e.target.closest('.add-btn'))return;showGameDetails(g)});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('.add-btn')){e.preventDefault();showGameDetails(g)}});add.addEventListener('click',e=>{e.stopPropagation();toggleCart(g)});}
byId('resultSummary').textContent=`${arr.length} لعبة`;
byId('activeFilters').textContent=[state.search?`بحث: ${state.search}`:'',state.platform==='PS5'&&state.catalogFilter!=='all'?`المنصة: ${state.catalogFilter}`:''].filter(Boolean).join(' • ');
renderPagination(totalPages);}
function renderPagination(totalPages){const el=byId('pagination');el.innerHTML='';const prev=button('السابق',state.page===1);prev.onclick=()=>{state.page--;renderGames();scrollCatalog()};el.appendChild(prev);const maxButtons=5;let s=Math.max(1,state.page-2),e=Math.min(totalPages,s+maxButtons-1);s=Math.max(1,e-maxButtons+1);for(let i=s;i<=e;i++){const b=button(String(i),false);if(i===state.page)b.classList.add('active');b.onclick=()=>{state.page=i;renderGames();scrollCatalog()};el.appendChild(b)}const next=button('التالي',state.page===totalPages);next.onclick=()=>{state.page++;renderGames();scrollCatalog()};el.appendChild(next);}
function button(text,disabled){const b=document.createElement('button');b.type='button';b.className='page-btn';b.textContent=text;b.disabled=disabled;return b}
function scrollCatalog(){byId('catalogSection').scrollIntoView({behavior:'smooth',block:'start'})}
function toggleCart(g){const i=state.cart.findIndex(x=>String(x.id)===String(g.id));if(i>=0){state.cart.splice(i,1);showToast('تمت إزالة اللعبة من الطلب');}else{state.cart.push(g);showToast('تمت إضافة اللعبة إلى الطلب');}saveCart();renderGames();renderCart();}
function renderCart(){byId('cartCount').textContent=state.cart.length;byId('cartTotalGames').textContent=state.cart.length;const total=state.cart.reduce((s,g)=>s+Number(g.size||0),0);byId('cartTotalSize').textContent=`${formatNumber(total)} GB`;const items=byId('cartItems');items.innerHTML='';byId('cartEmpty').classList.toggle('hidden',state.cart.length!==0);for(const g of state.cart){const row=document.createElement('div');row.className='cart-item';row.innerHTML=`<img class="cart-thumb" src="${escapeHtml(g.image)}" alt="${escapeHtml(g.name)}"><div class="cart-item-body"><p class="cart-item-title">[${escapeHtml(g.id)}] ${escapeHtml(g.name)}</p><div class="cart-item-meta">${escapeHtml(g.platform)} • ${escapeHtml(g.size)} GB</div><button class="remove-btn" data-remove-id="${escapeHtml(g.id)}" type="button">إزالة</button></div>`;items.appendChild(row);row.querySelector('[data-remove-id]').onclick=()=>toggleCart(g)}}
function formatNumber(n){return Number(n).toLocaleString('en-US',{maximumFractionDigits:2})}
function openCart(){byId('cartDrawer').classList.add('open');byId('cartDrawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeCart(){byId('cartDrawer').classList.remove('open');byId('cartDrawer').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function showGameDetails(g){const old=document.querySelector('.details-modal');if(old)old.remove();const m=document.createElement('div');m.className='details-modal';m.innerHTML=`<div class="drawer-backdrop" style="opacity:1"></div><section class="modal-card"><button class="icon-btn close-details" type="button">×</button><img src="${escapeHtml(g.image)}" alt="${escapeHtml(g.name)}"><div class="modal-copy"><span class="section-kicker">تفاصيل اللعبة</span><h2>${escapeHtml(g.name)}</h2><div class="detail-list"><div><span>رقم اللعبة</span><strong>${escapeHtml(g.id)}</strong></div><div><span>المنصة</span><strong>${escapeHtml(g.platform)}</strong></div><div><span>الحجم</span><strong>${escapeHtml(g.size)} GB</strong></div><div><span>سنة الإصدار</span><strong>${escapeHtml(g.releaseYear)}</strong></div><div><span>النوع</span><strong>${escapeHtml(g.genre)}</strong></div></div>${g.notes?`<p class="detail-notes">${escapeHtml(g.notes)}</p>`:''}<button class="primary-btn detail-add" type="button">${state.cart.some(x=>String(x.id)===String(g.id))?'إزالة من الطلب':'إضافة للطلب'}</button></div></section>`;document.body.appendChild(m);const close=()=>{m.remove()};m.querySelector('.close-details').onclick=close;m.querySelector('.drawer-backdrop').onclick=close;m.querySelector('.detail-add').onclick=()=>{toggleCart(g);close()}}
async function loadJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: ${r.status}`);return r.json()}
async function boot(){loadCart();if(location.protocol==='file:'){showLocalLoader();return;}try{const [games,config]=await Promise.all([loadJson('games.json'),loadJson('config.json')]);init(games,config)}catch(err){showFatal('تعذر تحميل بيانات الموقع. تأكد من وجود games.json و config.json بجانب ملفات الموقع.');console.error(err)}}
function showFatal(msg){document.body.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;padding:24px;background:#0b0d12;color:#f5f7fb;font-family:system-ui"><section style="max-width:560px;background:#121620;border:1px solid #252b38;padding:28px;border-radius:20px"><h1 style="margin-top:0">تعذر تحميل الموقع</h1><p style="color:#9ba3b5;line-height:1.8">${escapeHtml(msg)}</p></section></main>`}
function showLocalLoader(){const box=document.createElement('div');box.className='local-loader';box.id='localLoader';box.innerHTML=`<section class="local-loader-card"><span class="section-kicker">تشغيل محلي</span><h2>تحميل ملفات الموقع</h2><p>عند فتح index.html مباشرة بالنقر المزدوج، يمنع المتصفح قراءة JSON تلقائيًا. اختر الملفين مرة واحدة ليعمل الموقع محليًا. على GitHub Pages سيتم تحميلهما تلقائيًا.</p><div class="local-loader-grid"><div class="file-pick"><label for="localGames">games.json</label><input id="localGames" type="file" accept="application/json,.json"></div><div class="file-pick"><label for="localConfig">config.json</label><input id="localConfig" type="file" accept="application/json,.json"></div></div><button class="primary-btn" id="localStart" type="button" disabled>تشغيل الموقع</button></section>`;document.body.appendChild(box);let gf=null,cf=null;const check=()=>{byId('localStart').disabled=!(gf&&cf)};byId('localGames').onchange=e=>{gf=e.target.files[0]||null;check()};byId('localConfig').onchange=e=>{cf=e.target.files[0]||null;check()};byId('localStart').onclick=async()=>{try{const games=JSON.parse(await gf.text()),config=JSON.parse(await cf.text());box.remove();init(games,config)}catch(e){showToast('تأكد من صحة ملفي JSON')}}}
function init(games,config){if(!Array.isArray(games))throw new Error('games.json يجب أن يكون Array');state.games=games;state.config={...state.config,...(config||{})};byId('siteName').textContent=state.config.siteName||'كتالوج الألعاب';document.title=state.config.siteName||'كتالوج الألعاب';const hasPS3=state.games.some(g=>g.platform==='PS3');byId('ps3PlatformCard').classList.toggle('hidden',!hasPS3);byId('heroPS3Badge').classList.toggle('hidden',!hasPS3);byId('changePlatformBtn').classList.add('hidden');document.querySelectorAll('[data-platform]').forEach(b=>b.onclick=()=>selectPlatform(b.dataset.platform));byId('cartBtn').onclick=openCart;byId('closeCartBtn').onclick=closeCart;byId('drawerBackdrop').onclick=closeCart;byId('clearCartBtn').onclick=()=>{if(!state.cart.length)return;if(confirm('إفراغ سلة الطلب؟')){state.cart=[];saveCart();renderCart();renderGames()}};byId('sendWhatsAppBtn').onclick=sendWhatsApp;byId('searchInput').oninput=e=>{state.search=e.target.value;state.page=1;renderGames()};byId('sortSelect').onchange=e=>{state.sort=e.target.value;state.page=1;renderGames()};byId('platformFilter').onchange=e=>{state.catalogFilter=e.target.value;state.page=1;renderGames()};byId('changePlatformBtn').onclick=()=>{state.platform=null;byId('catalogSection').classList.add('hidden');byId('selectedPlatform').classList.add('hidden');byId('platformChooser').classList.remove('hidden');byId('changePlatformBtn').classList.add('hidden')};renderCart()}
function selectPlatform(platform){state.platform=platform;state.catalogFilter='all';state.page=1;state.search='';byId('searchInput').value='';byId('platformFilter').value='all';byId('platformChooser').classList.add('hidden');byId('selectedPlatform').classList.remove('hidden');byId('selectedPlatformLabel').textContent=platform;byId('selectedPlatformRule').textContent=platform==='PS4'?'ألعاب PS4 فقط':platform==='PS3'?'ألعاب PS3 فقط':'ألعاب PS4 وPS5';byId('catalogSection').classList.remove('hidden');byId('changePlatformBtn').classList.remove('hidden');renderGames();scrollCatalog()}
function sendWhatsApp(){if(!state.cart.length){showToast('السلة فارغة');return}const number=String(state.config.whatsappNumber||'').replace(/\D/g,'');if(!number||number.includes('XXXXXXXX')){showToast('ضع رقم واتساب الحقيقي في config.json');return}const total=state.cart.reduce((s,g)=>s+Number(g.size||0),0);const lines=['السلام عليكم','', 'أريد طلب تنصيب الألعاب التالية:','',...state.cart.map((g,i)=>`${i+1}. [${g.id}] ${g.name} — ${g.platform} — ${g.size} GB`),'',`عدد الألعاب: ${state.cart.length}`,`إجمالي المساحة: ${formatNumber(total)} GB`];const url=`https://wa.me/${number}?text=${encodeURIComponent(lines.join('\n'))}`;window.open(url,'_blank','noopener')}
boot();
